import {defineConfig} from "vite";
import path from "path";
module.exports = defineConfig({
    resolve: {
        alias: {
            '@': path.resolve(__dirname, '.', './src/'),
        },
    },
    build: {
        lib: {
            entry: path.resolve(__dirname, 'src/index.ts'),
            name: "{{repo_name}}",
            formats: ['es', 'umd'], // adding 'umd' requires globals set to every external module
            fileName: (format) => `{{repo_name}}.${format}.js`,
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});
