name: Publish to NPM
on:
  workflow_run:
    workflows: [ "Template Cleanup" ]
    types:
      - completed
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.check.outputs.token }}
    if: github.event.repository.name != 'ts-library-template'
    steps:
      - name: Check if NPM_TOKEN is set
        id: check
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "token=$( [ -n "$NPM_TOKEN" ] && echo true || echo false )">>$GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: prepare
    name: Publish to NPM
    if: github.event.repository.name != 'ts-library-template' && needs.prepare.outputs.token == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build
        run: pnpm run build
      - name: Pre Release
        run: node ./.github/scripts/pre-release.js
      - name: Semantic Release
        run: pnpm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Post Release
        run: node ./.github/scripts/post-release.js

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"
          # Push changes

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
